routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// --------------------------
//          Racine
// --------------------------
Route::get('/', 'FlagMapController@index')->name('map');



// -----------------------------------------
//   Routes d'authentification et middleware
// -----------------------------------------
Auth::routes();
Auth::routes(['verify' => true]); // Activer la vérification des adresses mails. Implement dans User.php
Route::get('home', 'HomeController@index')->name('home')->middleware('admin', 'throttle:5,1'); // Admin + anti bruteforce
Route::get('contribute', 'ContributeController@index')->name('contribute')->middleware('contribute', 'throttle:30,1'); // Abonnés + anti brute force


Route::resource('posts', 'PostController');

Route::get('/our_flags', 'FlagMapController@index')->name('flag_map.index');
Route::resource('flags', 'FlagController');

Route::middleware('verified')->group(function () {
	Route::resource('user', 'UserController');
	Route::middleware('auth', 'admin')->group(function () {
	    Route::get('photo', 'PhotoController@getForm');
	    Route::post('photo', 'PhotoController@postForm');
	});
});


// --------------------------
//   Administrateur
// --------------------------
Route::middleware('admin', 'throttle:5,1')->group(function () { // Anti bruteforce, 5 accès par minute
    Route::get('user.index', 'UserController@index');
    Route::get('user.create', 'UserController@create');
    Route::post('user.store', 'UserController@store');
    Route::put('user.update', 'UserController@update');
    Route::get('user.edit', 'UserController@edit');
    Route::delete('user.destroy', 'UserController@destroy');

    Route::get('posts.create', 'PostController@create');
    Route::post('posts.store', 'PostController@store');
    Route::put('posts.update', 'PostController@update');
    Route::get('posts.edit', 'PostController@edit');
});

Route::delete('posts.destroy', 'PostController@destroy')->middleware('admin');



// --------------------------
//        Tous publics
// --------------------------

// Page d'aide, FAQ
Route::get('aide', function () {
    return view('help');
});

// Formulaire de contact
Route::get('contact', 'ContactController@getForm');
Route::post('contact', 'ContactController@postForm');

// Inscription lettre d'information
Route::get('newsletter', 'NewsletterController@getForm');
Route::post('newsletter', ['uses' => 'NewsletterController@postForm', 'as' => 'storeEmail']);

Route::view('mention-legal', 'mention-legal');
Route::view('rgpd', 'rgpd');
Route::view('accessibilite', 'accessibilite');

resources/views/accessibilite.blade.php
@extends('layouts.template')

@section('titre')
	Accessibilité
@endsection

@section('contenu')

	<section>
		<article>
			<header id="header-content">
				<nav id="breadcrumb" aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
						<li class="breadcrumb-item" aria-current="page">Accessibilité</li>
					</ol>
				</nav>

				<h2>Accessibilité et bonnes pratiques</h2>
				<p><strong>Cette page est une déclaration de conformité au référentiel Opquast et WCAG qui vise à définir le niveau d’accessibilité général constaté sur le site.<br />
				Pour des aides relatives à la navigation et aux aménagements particuliers du site, visitez la page d’aide.</strong></p>
			</header>

			<p>La déclaration de conformité de OpenCyclo a été établie le jj/mm/aaaa.</p>
			<p>La version du référentiel Opquast utilisé est la version 2019.</p>

			<h3>Identité du déclarant</h3>
			<p>OpenCyclo</p>

			<h3>Technologies utilisées</h3>
			<ul>
			    <li>HTML5</li>
			    <li>CSS3</li>
				<li>JSON</li>
			    <li>JavaScript</li>
			    <li>PHP 7.2</li>
				<li>Laravel 6</li>
				<li>Leaflet</li>
				<li>Open Street Map</li>
				<li>Géolocalisation : Locate Control</li>
				<li>SwiftMailer</li>
			</ul>

		</article>
	</section>

@endsection

resources/views/confirm.blade.php
@extends('layouts.template')

@section('titre')
	Merci
@endsection

@section('sous-titre')
	<p>&nbsp;&laquo;La seule voie qui offre quelque espoir d'un avenir meilleur pour toute l'humanité est celle de la coopération et du partenariat.&nbsp;&raquo; - Kofi Annan</p>
@endsection

@section('contenu')

	<section class="content">
		<header id="header-content">
			<nav id="breadcrumb" aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
					<li class="breadcrumb-item" aria-current="page">Confirmation de reception</li>
				</ol>
			</nav>

			<h2>Nous avons bien reçu votre message</h2>
		</header>

		<p>Nos équipes vous répondrons dans les plus brefs délais.</p>
		<p>Retour à la <a class="active" href="{{ route('map') }}">carte</a>.</p>
	</section>

@endsection

resources/views/contact.blade.php
@extends('layouts.template')

@section('titre')
	Nous contacter
@endsection

@section('sous-titre')
	<p>&nbsp;&laquo;La seule voie qui offre quelque espoir d'un avenir meilleur pour toute l'humanité est celle de la coopération et du partenariat.&nbsp;&raquo; - Kofi Annan</p>
@endsection

@section('contenu')

	<section class="form-center">
		<header id="header-content">
			<nav id="breadcrumb" aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
					<li class="breadcrumb-item" aria-current="page">Nous contacter</li>
				</ol>
			</nav>

			<h2>Nous sommes à votre écoute</h2>

			<p>&laquo;&nbsp;Pédagogie&nbsp;&raquo;, voilà un mot qui revet un sens particulier chez OpenCyclo.<br />
			Nous mettons un point d'honneur à informer et à fournir des guides, pour un cyclisme en toute sécurité.<br />
			<a href="newsletter#header-content">Inscrivez-vous à notre newsletters</a></p>
		</header>

		{{ Form::open(['url' => 'contact']) }}
		<div class="{!! $errors->has('nom') ? 'has-error' : '' !!}">
			{{ Form::label('name', 'Nom', array('class' => 'hidden')) }}
			{{ Form::text('name', null, ['placeholder' => 'Votre nom', 'required']) }}
			{{ $errors->first('name', '<small class="help-block">:message</small>') }}
		</div>
		<div class="{!! $errors->has('email') ? 'has-error' : '' !!}">
			{{ Form::label('email', 'Email', array('class' => 'hidden')) }}
			{{ Form::email('email', null, ['placeholder' => 'Votre email'], 'required') }}
			{{ $errors->first('email', '<small class="help-block">:message</small>') }}
		</div>
		<div class="{!! $errors->has('texte') ? 'has-error' : '' !!}">
			{{ Form::label('mess', 'Message', array('class' => 'hidden')) }}
			{{ Form::textarea ('mess', null, ['placeholder' => 'Votre message', 'required']) }}
			{{ $errors->first('mess', '<small class="help-block">:message</small>') }}
		</div>
		{{ Form::submit('Envoyer !') }}
		{{ Form::close() }}

	</section>

@endsection

resources/views/editUser.blade.php
@extends('layouts.app')


@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			@if (Auth::user()->admin === 1)
				<li class="breadcrumb-item"><a href="{{ url('user') }}">Liste des membres</a></li>
			@endif
			<li class="breadcrumb-item" aria-current="page">Modifier</li>
		</ol>
	</nav>
@endsection


@section('content')

	<section class="base-page">

		<header>
			<h2>Modifier le profil</h2>
		</header>

		{{ Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put']) }}
		<div class="{!! $errors->has('name') ? 'has-error' : '' !!}">
			{{ Form::text('name', null, ['placeholder' => 'Nom', 'required']) }}
			{!! $errors->first('name', '<small>:message</small>') !!}
		</div>
		<div class="{!! $errors->has('email') ? 'has-error' : '' !!}">
			{{ Form::email('email', null, ['placeholder' => 'Email', 'required']) }}
			{!! $errors->first('email', '<small>:message</small>') !!}
		</div>

		@if (Auth::user()->admin === 1)
			<div class="checkbox">
				<label>
					{{ Form::checkbox('admin', 1, null) }} Administrateur
				</label>
			</div>
		@endif

		<div class="list-btn">
			{{ Form::submit('Envoyer', ['class' => 'btn']) }}
			{{ Form::close() }}

			@if (Route::has('password.request'))
			<a class="btn" href="{{ route('password.request') }}">
				{{ __('Changer mot de passe') }}
			</a>
			@endif

			{{ Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) }}
			{{ Form::submit('Résilier', ['class' => 'btn', 'onclick' => 'return confirm(\'Voulez-vous vraiment résilier votre accès ?\')']) }}
			{{ Form::close() }}
		</div>

	</section>

@endsection

resources/views/email_contact.blade.php
<!-- Old -->
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
	</head>

	<body>
		<h2>Formulaire de contact Opencyclo</h2>
		<p>{{ $name }} <<a href="mailto:{{ $email }}">{{ $email }}</a>></p>

		<p>{{ $mess }}</p>
	</body>
</html>

resources/views/help.blade.php
@extends('layouts.template')

@section('titre')
	Besoin d'aide ?
@endsection

@section('sous-titre')
	<p>&laquo;&nbsp;Il est plus facile de professer en paroles un humanisme de bon aloi, que de rendre service à son voisin&nbsp;&raquo; - Henri Laborit</p>
@endsection


@section('contenu')

	<section>
		<article>
			<header id="header-content">
				<nav id="breadcrumb" aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
						<li class="breadcrumb-item" aria-current="page">Aide</li>
					</ol>
				</nav>

				<h2><abbr title="Foire aux questions">FAQ</abbr></h2>
				<p>Vous assister en toutes circonstances. Si vous vous posez des questions, il y a des chances pour que vous trouviez une réponse ici même.<br />
				Si ce n'est pas le cas, contactez-nous via notre formulaire et nous répondrons dans les plus brefs délais.</p>
			</header>

			<h3>Qu'est-ce que Open cyclo&nbsp;?</h3>
			<p>Open cyclo est un service en ligne dédié aux cyclistes, qu'ils ou elles soient occasionnels ou expérimentés. Ce service propose une cartographique donnant une image clair des pistes cyclables, avec géolocalisation et ajout/affichage de signalements.</p>
			<p>Malgré l’augmentation des pistes cyclables, de nombreux cyclistes se trouvent en difficulté sur des pistes mal conçues ou dégradées.<br />
			Un affichage clair des travaux et des perturbations peut grandement faciliter la circulation.</p>
			<p>C'est enfin un outil de pédagogie et d'information.</p>

			<h3>Comment fonctionne notre service&nbsp;?</h3>
			<p>Pourquoi gratuit ? Notre service est open source, de plus vous ne trouverez aucune publicité. Open cyclo, c'est avant tout des passionnés et des gens un peu fou.</p>

			<h3>Comment ajouter un signalement sur la carte&nbsp;?</h3>
			<p>C'est très simple, pour ajouter un signalement vous devez être connecté. Pour cela, inscrivez-vous gratuitement avec votre pseudo et une adresse email, c'est tout !</p>
			<p>Une fois inscrit, vous êtes libre de contribuer et d'enrichir la carte Open cyclo.</p>

		</article>
	</section>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
	<section>

		@if (session('status'))
			<div class="alert alert-success" role="alert">
				{{ session('status') }}
			</div>
		@endif

		@if(session()->has('info'))
			<div class="notification is-success">
				{{ session('info') }}
			</div>
		@endif

		@if(session()->has('ok'))
			<div class="notification is-success">{!! session('ok') !!}</div>
		@endif

		<article>
			<header>
				<h2>{{ Auth::user()->name }} (<span>{!! link_to_route('user.edit', 'Modifier', [Auth::user()->id]) !!}</span>)</h2>
			</header>

			<p>Email : {{ Auth::user()->email }}<br />
				Rôle :
				@if (Auth::user()->admin === 1)
					Administrateur
				@else
					Abonné(e)
				@endif
			</p>
		</article>

		<article>
			<header>
				<h2>Carte</h2>
				<p>Gestion des signalements des abonné(e)s. Modification, suppression...</p>
			</header>

			<ul class="list-btn">
				<li>
					<a href="{{ route('flags.index') }}" class="btn">Tous les signalements</a>
				</li>
				<li>
					<a href="{{ route('flags.create') }}" class="btn">{{ __('Ajouter') }}</a>
				</li>
			</ul>
		</article>


		<article>
			<header>
				<h2>Articles</h2>
				<p>Ici vous pouvez créer, modifier, supprimer les articles du site Opencyclo.</p>
			</header>

			<ul class="list-btn">
				<li><a href="posts" class="btn">Tous les articles</a></li>
				<li><a href="{{ route('posts.create') }}" title="Formulaire d'ajout d'article" class="btn">Ajouter</a></li>
			</ul>
		</article>


		<article>
			<header>
				<h2>Membres</h2>
				<p>Gestion des abonnés et des rôles. Listing, modification, création, suppression...</p>
			</header>

			<ul class="list-btn">
				<li><a href="user" class="btn">Tous les utilisateurs</a></li>
				<li><a href="{{ route('user.create') }}" class="btn">{{ __('Ajouter') }}</a></li>
			</ul>
		</article>

	</section>
@endsection

resources/views/indexUsers.blade.php
@extends('layouts.app')


@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			<li class="breadcrumb-item" aria-current="page">Liste des membres</li>
		</ol>
	</nav>
@endsection


@section('content')
	<section class="base-page">

		<header>
			<h2>Liste des membres</h2>
			@if(Auth::check() and Auth::user()->admin)
				@can('create', new App\User)
					<p><a href="{{ route('user.create') }}">Ajouter un utilisateur</a></p>
				@endcan
			@endif
		</header>

		@if(session()->has('ok'))
			<div class="alert alert-success alert-dismissible">{!! session('ok') !!}</div>
		@endif

		@if(session()->has('info'))
			<div class="notification is-success">
				{{ session('info') }}
			</div>
		@endif

		<table class="table">
			<thead>
				<tr>
					<th>Nom</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach ($users as $user)
					<tr>
						<td><strong>{!! $user->name !!}</strong>
							@if($user->admin == 1)
							(<span>Admin</span>)
							@endif
						</td>
						<td>{!! link_to_route('user.show', 'Voir', [$user->id], ['class' => 'btn']) !!}</td>
						<td>{!! link_to_route('user.edit', 'Modifier', [$user->id], ['class' => 'btn']) !!}</td>
						<td>
							{!! Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) !!}
							{!! Form::submit('Supprimer', ['class' => 'btn', 'onclick' => 'return confirm(\'Vraiment supprimer cet utilisateur ?\')']) !!}
							{!! Form::close() !!}
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>

		{{ $users->links() }}

	</section>
@endsection

resources/views/mention-legal.blade.php
@extends('layouts.template')

@section('titre')
	Mentions légales
@endsection

@section('sous-titre')
	<p>Pour un web responsable, sûr et respectueux des utilisateurs</p>
@endsection

@section('contenu')

	<section>
	   <article>
		   <header id="header-content">
			   <nav id="breadcrumb" aria-label="breadcrumb">
				   <ol class="breadcrumb">
					   <li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
					   <li class="breadcrumb-item" aria-current="page">Mentions légales</li>
				   </ol>
			   </nav>

			   <h2>Mentions légales</abbr></h2>
			   <p><strong>Le service Open cyclo est une création de Sébastien Sénéchal, dans le cadre d'une formation. Il n'est pas référencé et le restera pour le moment.<br />
			   Ce projet est suceptible de prendre de l'ampleur dans les mois à venir.</strong></p>

		   </header>

		   <h3>Maitrise d'oeuvre et maitre d'ouvrage</h3>
		   <p>Sébastien Sénéchal<br />
		   Site internet : <a href="https://sebastiensenechal.com/" title="Site de Sébastien Sénéchal" target="_blank">https://sebastiensenechal.com</a></p>

		   <h3>Hébergement OVH</h3>
			<address>
				Siège social<br />
				2 rue Kellermann<br />
				59100 Roubaix<br />
				France
			</address>
			<p><a href="www.ovh.com" title="Site d'OVH" target="_blank">www.ovh.com</a></p>

			<h3>Protection de vos données</h3>
			<p>Le site internet sebastiensenechal.com est conçu dans le respect des utilisateurs et de leurs données personnelles.<br />
			Pour en savoir plus sur la politique de protection des données, rendez-vous sur la page dédiée au RGPD.</p>

	   </article>
	</section>

@endsection

resources/views/newsletter.blade.php
@extends('layouts.template')

@section('titre')
	Inscription à la newsletter
@endsection

@section('contenu')

	<section class="form-center">
		<header id="header-content">
			<nav id="breadcrumb" aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
					<li class="breadcrumb-item" aria-current="page">Inscription à la newsletter</li>
				</ol>
			</nav>

			<h2>Restez informé avec OpenCyclo</h2>
			<p>Recevez les dernières informations et les bons plans, pour un cyclisme agréable et civique.</p>
		</header>

		{!! Form::open(['route' => 'storeEmail']) !!}
		<div class="{!! $errors->has('email') ? 'has-error' : '' !!}">
			{!! Form::email('email', null, array('placeholder' => 'Entrez votre email')) !!}
			{!! $errors->first('email', '<small class="help-block">:message</small>') !!}
		</div>
		{!! Form::submit('Envoyer !', ['class' => 'btn']) !!}
		{!! Form::close() !!}

	</section>

@endsection

resources/views/newsletterConfirm.blade.php
@extends('layouts.template')

@section('titre')
	Confirmation d'inscription
@endsection

@section('contenu')

	<section class="content">
		<header id="header-content">
			<nav id="breadcrumb" aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
					<li class="breadcrumb-item" aria-current="page">Confirmation</li>
				</ol>
			</nav>

			<h2>Confirmation</h2>
		</header>

		<p>Merci. Votre adresse a bien été prise en compte.</p>
	</section>

@endsection

resources/views/photo.blade.php
@extends('layouts.template')

@section('titre')
	Importer une photo
@endsection

@section('contenu')

	<section class="form-center">
		@if(session()->has('error'))
			<div>{!! session('error') !!}</div>
		@endif

		{!! Form::open(['url' => 'photo', 'files' => true]) !!}
		<div class="{!! $errors->has('image') ? 'has-error' : '' !!}">
			{!! Form::file('image', ['class' => 'form-control']) !!}
			{!! $errors->first('image', '<small class="help-block">:message</small>') !!}
		</div>

		{!! Form::submit('Envoyer !', ['class' => 'btn']) !!}
		{!! Form::close() !!}
	</section>

@endsection

resources/views/rgpd.blade.php
@extends('layouts.template')

@section('titre')
	Données personnelles<br />(RGPD)
@endsection

@section('sous-titre')
	<p>Votre vie privée ainsi que vos données personnelles vous appartiennent. Elles possèdent un caractère sacré qui doit être respecté.</p>
@endsection

@section('contenu')

	<section>
		<article>
			<header id="header-content">
				<nav id="breadcrumb" aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
						<li class="breadcrumb-item" aria-current="page">RGPD</li>
					</ol>
				</nav>

				<h2>Réglement général pour la protection des données <abbr title="Réglement général pour la protection des données">RGPD</abbr></h2>
				<p><strong>Vos données peuvent faire l’objet d’un traitement, notamment dans le cadre du suivi de fréquentation.
				Lorsque certaines informations sont obligatoires pour accéder à des fonctionnalités spécifiques, ce caractère obligatoire est indiqué au moment de la collecte de la saisie des données.
				Je ne collecte que le strict minimum et les adresses IP sont cryptées et anonymisées par Google Analytics.</strong></p>
			</header>

			<h3>Données enregistrées</h3>
			<p>Des données à caractère personnel sont susceptibles d’être collectées par Open Cyclo.</p>
			<ul>
				<li>Nom</li>
				<li>Prénom</li>
				<li>Adresse email</li>
			</ul>

			<p>Dans le cadre :</p>
			<ul>
				<li>D'un formulaire de contact</li>
				<li>D'une inscription sur le site Open cyclo</li>
				<li>D'une inscription à notre lettre d'information</li>
			</uL>

			<h3>Durée de conservation des données</h3>
			<p>Vos données ne sont conservées qu'au strict minimum.<br />
			En cas d'inactivité, les données sont supprimées au bout d'un an, dans le cadre du droit à l'oublie.</p>

			<h3>Droit des personnes</h3>
			<p>Conformément aux dispositions légales et règlementaires applicables, en particulier la loi n° 78-17 du 6 janvier modifiée relative à l’informatique, aux fichiers et aux libertés et le règlement européen n° 2016/679/UE du 27 avril 2016 (applicable depuis le 25 mai 2018), vous disposez des droits suivants :</p>
			<ul>
				<li>Exercer votre droit d’accès, pour connaître les données personnelles qui vous concernent ;</li>
			    <li>Demander la mise à jour de vos données, si elles sont inexactes ;</li>
			    <li>Demander la portabilité ou la suppression de vos données ;</li>
			    <li>Vous opposer, pour des motifs légitimes, au traitement de vos données ;</li>
			    <li>Retirer votre consentement au traitement de vos données.</li>
			</ul>

			<h3>Pour exercer ces droits</h3>
			<p>Contactez-nous directement sur notre formulaire de contact</p>

			<h3>Réclamation</h3>
			<p>Si vous estimez, après nous avoir contactés, que vos droits Informatique et Libertés ne sont pas respectés, vous avez la possibilité d’introduire une réclamation auprès de la CNIL.</p>
		</article>
	</section>

@endsection

resources/views/showUser.blade.php
@extends('layouts.app')


@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			<li class="breadcrumb-item"><a href="{{ url('user') }}">Liste des membres</a></li>
			<li class="breadcrumb-item" aria-current="page">{{ $user->name }}</li>
		</ol>
	</nav>
@endsection


@section('content')
	<section class="base-page">

		<header>
			<h2>Profil de {{ $user->name }}</h2>
		</header>

		<p>Nom : {{ $user->name }}</p>
		<p>Email : {{ $user->email }}</p>
		@if($user->admin == 1)
			<p>Rôle : Administrateur</p>
		@endif

		<p><a href="javascript:history.back()" class="btn">Retour</a></p>

	</section>
@endsection