routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// --------------------------
//          Racine
// --------------------------
Route::get('/', 'FlagMapController@index')->name('map');



// -----------------------------------------
//   Routes d'authentification et middleware
// -----------------------------------------
Auth::routes();
Auth::routes(['verify' => true]); // Activer la vérification des adresses mails. Implement dans User.php
Route::get('home', 'HomeController@index')->name('home')->middleware('admin', 'throttle:5,1'); // Admin + anti bruteforce
Route::get('contribute', 'ContributeController@index')->name('contribute')->middleware('contribute', 'throttle:30,1'); // Abonnés + anti brute force


Route::resource('posts', 'PostController');

Route::get('/our_flags', 'FlagMapController@index')->name('flag_map.index');
Route::resource('flags', 'FlagController');

Route::middleware('verified')->group(function () {
	Route::resource('user', 'UserController');
	Route::middleware('auth', 'admin')->group(function () {
	    Route::get('photo', 'PhotoController@getForm');
	    Route::post('photo', 'PhotoController@postForm');
	});
});


// --------------------------
//   Administrateur
// --------------------------
Route::middleware('admin', 'throttle:5,1')->group(function () { // Anti bruteforce, 5 accès par minute
    Route::get('user.index', 'UserController@index');
    Route::get('user.create', 'UserController@create');
    Route::post('user.store', 'UserController@store');
    Route::put('user.update', 'UserController@update');
    Route::get('user.edit', 'UserController@edit');
    Route::delete('user.destroy', 'UserController@destroy');

    Route::get('posts.create', 'PostController@create');
    Route::post('posts.store', 'PostController@store');
    Route::put('posts.update', 'PostController@update');
    Route::get('posts.edit', 'PostController@edit');
});

Route::delete('posts.destroy', 'PostController@destroy')->middleware('admin');



// --------------------------
//        Tous publics
// --------------------------

// Page d'aide, FAQ
Route::get('aide', function () {
    return view('help');
});

// Formulaire de contact
Route::get('contact', 'ContactController@getForm');
Route::post('contact', 'ContactController@postForm');

// Inscription lettre d'information
Route::get('newsletter', 'NewsletterController@getForm');
Route::post('newsletter', ['uses' => 'NewsletterController@postForm', 'as' => 'storeEmail']);

Route::view('mention-legal', 'mention-legal');
Route::view('rgpd', 'rgpd');
Route::view('accessibilite', 'accessibilite');

app/Flag.php
<?php
namespace App;

use App\Flag;
use Illuminate\Database\Eloquent\Model;

class Flag extends Model
{
	/**
	* The attributes that are mass assignable.
	*
	* @var array
	*/
	protected $fillable = [
		'name', 'latitude', 'longitude', 'creator_id',
	];
	/**
	* The accessors to append to the model's array form.
	*
	* @var array
	*/
	public $appends = [
		'coordinate', 'map_popup_content',
	];
	/**
	* Get Flag name_link attribute.
	*
	* @return string
	*/
	public function getNameLinkAttribute()
	{
		$title = __('En savoir plus', [
			'name' => $this->name, 'type' => __('flag.flag'),
		]);
		$link = '<a href="'.route('flags.show', $this).'"';
		$link .= ' title="'.$title.'">';
		$link .= $this->name;
		$link .= '</a>';
		return $link;
	}
	/**
	* Flag belongs to User model relation.
	*
	* @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	*/
	public function creator()
	{
		return $this->belongsTo(User::class);
	}
	/**
	* Get Flag coordinate attribute.
	*
	* @return string|null
	*/
	public function getCoordinateAttribute()
	{
		if ($this->latitude && $this->longitude) {
			return $this->latitude.', '.$this->longitude;
		}
	}
	/**
	* Get Flag map_popup_content attribute.
	*
	* @return string
	*/
	public function getMapPopupContentAttribute()
	{
		$mapPopupContent = '';
		$mapPopupContent .= "<p><strong>".$this->name_link."</strong></p>";
		if ($this->name == "Travaux") {
			$mapPopupContent .= "<p>Risque de travaux sur la voie publique, soyez prudent.</p>";
		}
		if ($this->name == "Voie endommagée") {
			$mapPopupContent .= "<p>Route dégradée, nid-de-poule, dégats.<br>Roulez avec prudence.</p>";
		}
		if ($this->name == "Autre perturbation") {
			$mapPopupContent .= "<p>Attention, on nous signale une perturbation sur votre parcours.<br>Soyez prudent.</p>";
		}

		return $mapPopupContent;
	}
}

app/Http/Controllers/Api/FlagController.php
<?php

namespace App\Http\Controllers\Api;

use App\Flag;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\Flag as FlagResource;

class FlagController extends Controller
{
    /**
    * Get flag listing on Leaflet JS geoJSON data structure.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return Illuminate\Http\JsonResponse
    */
    public function index(Request $request)
    {
        $flags = Flag::all();

        $geoJSONdata = $flags->map(function ($flag) {
            return [
                'type'       => 'Feature',
                'properties' => new FlagResource($flag),
                'geometry'   => [
                    'type'        => 'Point',
                    'coordinates' => [
                        $flag->longitude,
                        $flag->latitude,
                    ],
                ],
            ];
        });

        return response()->json([
            'type'     => 'FeatureCollection',
            'features' => $geoJSONdata,
        ]);
    }
}

app/Http/Controllers/FlagController.php
<?php

namespace App\Http\Controllers;

use App\Flag;
use App\User;
use Auth;
use App\Http\Requests\FlagRequest;
use Illuminate\Http\Request;

class FlagController extends Controller
{
    /**
    * Display a listing of the flag.
    *
    * @return \Illuminate\View\View
    */
    public function index(User $user)
    {
        $this->authorize('manage_flag');
        $flagQuery = Flag::query();
        $flagQuery->where('name', 'like', '%'.request('q').'%');
        $flags = $flagQuery->paginate(10);

        return view('flags.index', compact('flags'));
    }
    /**
    * Show the form for creating a new flag.
    *
    * @return \Illuminate\View\View
    */
    public function create()
    {
        $this->authorize('create', new Flag);
        return view('flags.create');
    }
    /**
    * Store a newly created flag in storage.
    *
    * @param  App\Http\Requests\FlagRequest  $flagRequest
    * @return \Illuminate\Routing\Redirector
    */
    public function store(FlagRequest $flagRequest)
    {
        $this->authorize('create', new Flag);

        $newFlag = $flagRequest->all();
        $newFlag['creator_id'] = auth()->id();

        $flag = Flag::create($newFlag);

        return redirect()->route('flags.show', $flag);
    }
    /**
    * Display the specified flag.
    *
    * @param  \App\Flag  $flag
    * @return \Illuminate\View\View
    */
    public function show(Flag $flag)
    {
        return view('flags.show', compact('flag'));
    }
    /**
    * Show the form for editing the specified flag.
    *
    * @param  \App\Flag  $flag
    * @return \Illuminate\View\View
    */
    public function edit(Flag $flag)
    {
        $this->authorize('update', $flag);
        return view('flags.edit', compact('flag'));
    }
    /**
    * Update the specified flag in storage.
    *
    * @param  App\Http\Requests\FlagRequest  $flagRequest
    * @param  \App\Flag  $flag
    * @return \Illuminate\Routing\Redirector
    */
    public function update(FlagRequest $flagRequest, Flag $flag)
    {
        $this->authorize('update', $flag);

        $flagData = $flagRequest->all();
        $flag->update($flagData);

        return redirect()->route('flags.show', $flag);
    }
    /**
    * Remove the specified flag from storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Flag  $flag
    * @return \Illuminate\Routing\Redirector
    */
    public function destroy(Request $request, Flag $flag)
    {
        $this->authorize('delete', $flag);
        $request->validate(['flag_id' => 'required']);
        if ($request->get('flag_id') == $flag->id && $flag->delete()) {
            return redirect()->route('flags.index');
        }
        return back();
    }
}

resources/views/flags/create.blade.php
@extends('layouts.app')

@section('title', __('Ajouter un signalement'))

@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			<li class="breadcrumb-item"><a href="{{ url('flags') }}">Liste des signalements</a></li>
			<li class="breadcrumb-item" aria-current="page">Ajouter</li>
		</ol>
	</nav>
@endsection

@section('content')
	<section class="base-page duo">
		<article>
			<header>
				<h2>Ajouter un signalement</h2>
			</header>

			<form class="form-column" method="POST" action="{{ route('flags.store') }}" accept-charset="UTF-8">
				{{ csrf_field() }}

				<label for="name" class="control-label text-primary">{{ __('Type d\'incident') }}</label>
				<select id="name" class="{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" required>
					<option selected value="Travaux">Travaux</option>
					<option value="Voie endommagée">Voie endommagée</option>
					<option value="Autre perturbation">Autre perturbation</option>
				</select>
				{!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}


				<label for="latitude" class="control-label text-primary">{{ __('Latitude') }}</label>
				<input id="latitude" type="text" class="form-control{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', request('latitude')) }}" placeholder="Latitude..." required>
				{!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}


				<label for="longitude" class="control-label text-primary">{{ __('Longitude') }}</label>
				<input id="longitude" type="text" class="form-control{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', request('longitude')) }}" placeholder="Longitude..." required>
				{!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}


				<div id="mapid"></div>

				<div class="list-btn">
					<input type="submit" value="{{ __('Ajouter') }}" class="btn btn-success">
					@if(Auth::check() and Auth::user()->admin)
					<a href="{{ route('flags.index') }}" class="btn btn-link">{{ __('Annuler') }}</a>
					@else
					<a href="{{ route('map') }}" class="btn btn-link">{{ __('Annuler') }}</a>
					@endif
				</div>
			</form>

		</article>

	</section>
@endsection

@section('styles')
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
	integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
	crossorigin=""/>
@endsection

@push('scripts')
	<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
	integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
	crossorigin=""></script>

	{{ Html::script('js/MapsCreate.js') }}

	<script>
		MapsCreate.initMap();
	</script>
@endpush

resources/views/flags/edit.blade.php
@extends('layouts.app')

@section('title', __('Modifier'))


@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			<li class="breadcrumb-item"><a href="{{ url('flags') }}">Liste des signalements</a></li>
			<li class="breadcrumb-item" aria-current="page">Modifier</li>
		</ol>
	</nav>
@endsection


@section('content')
	<section class="base-page duo">
		@if (request('action') == 'delete' && $flag)
		@can('delete', $flag)
		<article>
			<header>
				<h2>Supprimer un signalement</h2>
			</header>

			<label class="control-label text-primary">{{ __('Type d\'incident') }}</label>
			<p>{{ $flag->name }}</p>
			<label class="control-label text-primary">{{ __('Latitude') }}</label>
			<p>{{ $flag->latitude }}</p>
			<label class="control-label text-primary">{{ __('Longitude') }}</label>
			<p>{{ $flag->longitude }}</p>
			{!! $errors->first('flag_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}

			<div class="list-btn">
				<form method="POST" action="{{ route('flags.destroy', $flag) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('Voulez-vous vraimer supprimer ?') }}&quot;)">
					{{ csrf_field() }} {{ method_field('delete') }}
					<input name="flag_id" type="hidden" value="{{ $flag->id }}">
					<button type="submit" class="btn btn-danger">{{ __('Confirmer la suppression') }}</button>
				</form>
				<a href="{{ route('flags.edit', $flag) }}" class="btn btn-link">{{ __('Annuler') }}</a>
			</div>
		</article>
		@endcan

		@else
		<article>
			<header>
				<h2>Modifier un signalement</h2>
			</header>
			<form class="form-column" method="POST" action="{{ route('flags.update', $flag) }}" accept-charset="UTF-8">
				{{ csrf_field() }} {{ method_field('patch') }}


				<label class="control-label text-primary" for="name">{{ __('Type d\'incident') }}</label><br>
				<select id="name" class="{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" required>
					<option selected value="Travaux">Travaux</option>
					<option value="Voie endommagée">Voie endommagée</option>
					<option value="Autre perturbation">Autre perturbation</option>
				</select>
				<!-- <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $flag->name) }}" required> -->
				{!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}


				<label class="control-label text-primary" for="latitude">{{ __('Latitude') }}</label>
				<input id="latitude" type="text" class="{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', $flag->latitude) }}" required>
				{!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}

				<label class="control-label text-primary" for="longitude">{{ __('Longitude') }}</label>
				<input id="longitude" type="text" class="{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', $flag->longitude) }}" required>
				{!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}


				<div id="mapid"></div>

				<div class="list-btn">
					<input type="submit" value="{{ __('Mettre à jour') }}" class="btn">
					<a href="{{ route('flags.show', $flag) }}" class="btn">{{ __('Annuler') }}</a>
					@can('delete', $flag)
					<a href="{{ route('flags.edit', [$flag, 'action' => 'delete']) }}" id="del-flag-{{ $flag->id }}" class="btn-link btn-danger">{{ __('Supprimer') }}</a>
					@endcan
				</div>
			</form>
		</article>
	</section>
@endif
@endsection

@section('styles')
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
	integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
	crossorigin=""/>
@endsection

@push('scripts')
	<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
	integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
	crossorigin=""></script>

	{{ Html::script('js/MapsCreate.js') }}

	<script>
		MapsCreate.initMap();
	</script>
@endpush

resources/views/flags/index.blade.php
@extends('layouts.app')

@section('title', __('Liste des signalements'))


@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			<li class="breadcrumb-item" aria-current="page">Liste des signalements</li>
		</ol>
	</nav>
@endsection



@section('content')
	<section class="base-page">

		<header>
			<h2 class="page-title">Liste des signalements <small>({{ $flags->total() }})</small></h2>
			@can('create', new App\Flag)
			<p><a href="{{ route('flags.create') }}">{{ __('Ajouter') }}</a></p>
			@endcan
		</header>

		<form method="GET" action="" accept-charset="UTF-8" class="form-inline">
			<div class="form-group">
				<label class="hidden" for="q" class="control-label">{{ __('Recherche') }}</label>
				<input placeholder="Rechercher..." name="q" type="text" id="q" value="{{ request('q') }}">
			</div>
			<input type="submit" value="Valider" class="btn">
			<a href="{{ route('flags.index') }}" class="btn">{{ __('Effacer') }}</a>
		</form>

		<table class="table table-sm table-responsive-sm">
			<thead>
				<tr>
					<th>{{ __('Identifiant') }}</th>
					<th>{{ __('Type d\'incident') }}</th>
					<th>{{ __('Latitude') }}</th>
					<th>{{ __('Longitude') }}</th>
					<th>{{ __('Action') }}</th>
				</tr>
			</thead>
			<tbody>
				@foreach($flags as $key => $flag)
				<tr>
					<td># {{ $flags->firstItem() + $key }}</td>
					<td>{!! $flag->name_link !!}</td>
					<td>{{ $flag->latitude }}</td>
					<td>{{ $flag->longitude }}</td>
					<td>
						<a href="{{ route('flags.show', $flag) }}" id="show-flag-{{ $flag->id }}">{{ __('Voir') }}</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>

		<!-- Pagination -->
		{{ $flags->appends(Request::except('page'))->render() }}

	</section>
@endsection

resources/views/flags/map.blade.php
@extends('layouts.home')

@section('nav')
	<h1 id="title-home">Opencyclo</h1>
	<nav id="nav">
		<ul class="navbar-nav ml-auto">
			<li class="deroulant"><span class="label_menu">Menu</span>
				<ul class="sous">
					<li><a class="active" href="{{ route('map') }}" title="Carte"><span class="material-icons">map</span> Carte</a></li>
					<li><a href="{{ url('posts') }}" title="Rester informé"><span class="material-icons">info</span> Infos cyclo</a></li>
					<li><a href="aide" title="Demander de l'aider"><span class="material-icons">help_outline</span> Aide</a></li>
					<li><a href="{{ url('contact') }}" title="Nous contacter"><span class="material-icons">mail_outline</span> Contact</a></li>
				</ul>
			</li>
		</ul>
	</nav>
@endsection

@section('content')
	<section id="intro">
		<header>
			<h2>Le guide tout-terrain</h2>
		</header>
		<article>
			<h3>Vous êtes cycliste, juste curieux&nbsp;?</h3>
			<ul>
				<li>Localisez votre position,</li>
				<li>Repérez les pistes cyclables,</li>
				<li>Informez-vous sur l'état des pistes,</li>
				<li>Contribuez.</li>
			</ul>
			<p>Le service est entièrement <strong>gratuit</strong>.<br />
			Pour contribuez <a href="{{ route('register') }}">inscrivez-vous</a>.</p>
		</article>
	</section>

	<div id="mapid"></div>

@endsection

@section('footer')
	<nav id="toolbar">
		<ul>
			<li><a href="{{ url('contact') }}" title="Nous contacter"><span class="material-icons">mail_outline</span></a></li>
			<li><a href="aide" title="Trouver de l'aide"><span class="material-icons">help_outline</span></a></li>
			<li><a href="contribute" title="Profil"><span class="material-icons">person</span></a></li>
		</ul>
	</nav>
@endsection

@section('styles')
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
	integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
	crossorigin=""/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.css" />
@endsection

@push('scripts')
	<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
	integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
	crossorigin=""></script>
	<script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.js"></script>

	{{ Html::script('js/Maps.js') }}

	<script>
		Maps.initMap();
		Maps.geoJson(); // Display markers on map
		@can('create', new App\Flag) // Authorization for addMarker
			Maps.addMarker();
		@endcan
	</script>
@endpush

resources/views/flags/show.blade.php
@extends('layouts.app')

@section('title', __('Détails'))


@section('header')
	<nav id="breadcrumb" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{{ route('map') }}">Accueil</a></li>
			<li class="breadcrumb-item"><a href="{{ route('home') }}">Tableau de bord</a></li>
			<li class="breadcrumb-item"><a href="{{ url('flags') }}">Liste des signalements</a></li>
			<li class="breadcrumb-item" aria-current="page">Détails</li>
		</ol>
	</nav>
@endsection


@section('content')
	<section class="base-page duo">
		<article>
			<header>
				<h2>Détails</h2>
			</header>

			<table class="table table-sm">
				<tbody>
					<tr><td class="text-primary">{{ __('Type d\'incident') }}</td><td>{{ $flag->name }}</td></tr>
					<tr><td class="text-primary">{{ __('Latitude') }}</td><td>{{ $flag->latitude }}</td></tr>
					<tr><td class="text-primary">{{ __('Longitude') }}</td><td>{{ $flag->longitude }}</td></tr>
				</tbody>
			</table>

			<ul class="list-btn">
				@if(Auth::check() and Auth::user()->admin)
				<li><a href="{{ route('flags.edit', $flag) }}" id="edit-flag-{{ $flag->id }}" class="btn">{{ __('Modifier') }}</a></li>
				<li><a href="{{ route('flags.index') }}" class="btn">{{ __('Liste') }}</a></li>
				@endif
				<li><a href="{{ route('map') }}" class="btn">{{ __('Carte') }}</a></li>
			</ul>
		</article>

		<aside>
			@if ($flag->coordinate)
			<div id="mapid"></div>
			@else
			<div>{{ __('flag.no_coordinate') }}</div>
			@endif
		</aside>
	</section>
@endsection

@section('styles')
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
	integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
	crossorigin=""/>
@endsection

@push('scripts')
	<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
	integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
	crossorigin=""></script>

	{{ Html::script('js/MapsShow.js') }}

	<script>
		MapsShow.initMap([{{ $flag->latitude }}, {{ $flag->longitude }}]);
	</script>
@endpush